name: "Deploy project to Google App Engine"
description: "This action allows you publish an application to Google App Engine"

inputs:
  service_account_email:
    description: "The service account email which will be used for authentication."
    required: true

  service_account_key:
    description: "The service account key which will be used for authentication."
    required: true

  project_id:
    description: "GAE project id"
    required: true

  gae_config_path:
    description: "Location of Google App Engine config file"
    required: false

  gae_variables:
    description: "GAE variables to be written to the app.yaml file"
    required: false

runs:
  using: "node12"
  main: "index.js"

branding:
  icon: "award"
  color: "blue"
